name:                aimcore
version:             0.1.0.0
github:              "githubuser/aimcore"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aimcore#readme>

default-extensions:
- BinaryLiterals
- DataKinds
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications
- TypeOperators
- DeriveAnyClass
- DeriveGeneric
- MultiParamTypeClasses
- AllowAmbiguousTypes
- PackageImports
- RecordWildCards
- GeneralizedNewtypeDeriving
- DerivingStrategies

dependencies:
- base >= 4.7 && < 5
- clash-prelude >= 1.8.1
- composition
- mtl >= 2.2.2
- transformers
- pretty
- tasty
- tasty-hunit
- tasty-quickcheck
- containers
- ghc-typelits-natnormalise
- array
- melf
- bytestring
- exceptions
- entropy
- binary
- pantomime
- pantomime-clash
- pantomime-base
- template-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fexpose-all-unfoldings
- -fplugin GHC.TypeLits.Normalise
- -fplugin Pantomime

library:
  source-dirs:
    - src
    - proof
  exposed-modules:
    - Proof.Machine
    - Proof.Driver
    - Proof.ISAStep
    - Proof.Functional.Invariant
    - Proof.Functional.Obligation
    - Proof.Functional.Induction
    - Proof.Leakage.Model
    - Proof.Leakage.Simulator
    - Proof.Leakage.Obligation
    - Proof.Leakage.Induction
    - Proof.SMT.Array
    - Proof.SMT.Axioms
    - Proof.SMT.Logged
    - Proof.SMT.Sanity
    - Access
    - Core
    - Elf.ElfLoader
    - Elf.Syscall
    - HardwareSim
    - Instruction
    - Interp
    - ISA
    - Memory.Types
    - Memory.Vec
    - Memory.ST
    - Memory.IO
    - Leak.Arch.Arch
    - Leak.PC.ISA
    - Leak.PC.Leak
    - Leak.PC.PC
    - Leak.PC.Sim
    - Leak.PCWithState.PCWithState
    - Leak.SecretPC.Leak
    - Leak.SecretPC.PC
    - Leak.MonitorPC.MonitorLeak
    - Leak.MonitorPC.PC
    - Leak.MonitorPC.Sim
    - Leak.Existence
    - Pretty
    - RegFile
    - Simulate
    - Types
    - Util

executables:
  aimcore-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aimcore
    - optparse-applicative
    - binary
    - blake2

tests:
  aimcore-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aimcore
    - melf
    - bytestring
    - exceptions
    - QuickCheck
