{-# LANGUAGE TupleSections #-}

module HardwareSim () where

-- import Clash.Prelude hiding (Log, Ordering (..), Word, def, init, lift, log)
-- import Clash.Sized.Vector (unsafeFromList)
-- import Control.Monad
-- import Control.Monad.IO.Class
-- import Control.Monad.RWS
-- import Control.Monad.State
-- import Control.Monad.Writer
-- import Data.Bifunctor
-- import Data.Either
-- import Data.Maybe (fromMaybe)
-- import Data.Monoid
-- import qualified Debug.Trace as DB
-- import Instruction hiding (decode)
-- import Pipe
-- import Regfile
-- import qualified Simulate
-- import Text.Read (readMaybe)
-- import Types
-- import Prelude hiding (Ordering (..), Word, init, log, map, not, repeat, take, undefined, (!!), (&&), (++), (||))
-- import qualified Prelude

-- simN :: Vec m Word -> Int -> [Either Output Word]
-- simN prog n = sampleN @System n $ system prog
--
-- simToHalt :: Vec m Word -> Word
-- simToHalt prog =
--   Prelude.head $ rights $ simN prog maxBound
--
-- cpu :: (HiddenClockResetEnable dom) => Signal dom Input -> Signal dom Output
-- cpu = mealy pipe initPipe
--
-- system :: (HiddenClockResetEnable dom) => Vec m Word -> Signal dom (Either Output Word)
-- system prog = out
--   where
--     out =
--       mux
--         (fromMaybe False . getFirst . outHalt <$> cpuOut)
--         (Right <$> ram)
--         (Left <$> cpuOut)
--     cpuInput = register initInput input
--     cpuOut = cpu cpuInput
--     regfile = mkRegfile $ mkRegAccess <$> cpuOut
--     ram = mkRAM prog (mkMemRead <$> cpuOut) (mkMemWrite <$> cpuOut)
--     input = (\mread (rs1, rs2) -> Input mread rs1 rs2) <$> ram <*> regfile
--     mkMemRead = maybe 0 memAddress . getFirst . outMem
--     mkMemWrite = ((\ma -> (memAddress ma,) <$> memVal ma) =<<) . getFirst . outMem
--     mkRegAccess (Output _ mr1 mr2 mrd _) =
--       RegAccess
--         { regRs1 = fromMaybe 0 $ getFirst mr1,
--           regRs2 = fromMaybe 0 $ getFirst mr2,
--           regRd = fromMaybe (0, 0) $ getFirst mrd
--         }
--
-- data RegAccess = RegAccess
--   { regRs1 :: RegIdx,
--     regRs2 :: RegIdx,
--     regRd :: (RegIdx, Word)
--   }
--   deriving (Show, Generic, NFDataX)
--
-- mkRegfile :: (HiddenClockResetEnable dom) => Signal dom RegAccess -> Signal dom (Word, Word)
-- mkRegfile input = mkOutput <$> reg_update <*> input
--   where
--     reg_output = register initRF reg_update
--     reg_update = ((uncurry modifyRF . regRd) <$> input) <*> reg_output
--     mkOutput rf (RegAccess rs1 rs2 _) = (lookupRF rs1 rf, lookupRF rs2 rf)
--
-- mkRAM ::
--   (HiddenClockResetEnable dom) =>
--   Vec m Word ->
--   Signal dom Address ->
--   Signal dom (Maybe (Address, Word)) ->
--   Signal dom Word
-- mkRAM = blockRam . Simulate.mkRAM
--
-- prog1 =
--   map encode $
--     -- r2 := r0 + 5
--     IType (Arith ADD) 2 0 5
--       :>
--       -- mem[0 + r0] := r2
--       SType Word 0 0 2
--       :> halt
--       :> Nil
--
-- sumTo :: Int -> Vec 8 Word
-- sumTo n =
--   map encode $
--     unsafeFromList
--       [ -- r1 := r0 + n
--         IType (Arith ADD) 1 0 $ fromIntegral n,
--         -- r2 := 0 (res = 0)
--         IType (Arith ADD) 2 0 0,
--         -- r1 == r0 ? jump pc + 4
--         BType EQ 4 1 0,
--         -- r2 := r2 + r1 (res += n)
--         RType ADD 2 2 1,
--         -- r1 := r1 - 1 (n -= 1)
--         IType (Arith ADD) 1 1 (-1),
--         -- jump back to the branch
--         JType 0 (-3),
--         -- mem[0] := r2
--         SType Word 0 0 2,
--         halt
--       ]
